version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist
    overwrite: true
hooks:
  AfterInstall:
    - location: pipeline/install_dependencies
      timeout: 1800
      runas: root
